import 'dart:convert';

import 'package:auth_register/fetchData/dashboard_data_response_model.dart';
import 'package:http/http.dart';
import 'package:http/http.dart' as http;

class ApiProvider {
  //final Dio _dio = Dio();
  //final String _url = 'https://reqres.in/api/users?page=1';
  final String _url = 'https://api.besttutor.xyz/api/tutor/dashboard';
  final String token = '8970|jbP29Yd7xj9hSgG8IWt7QSG8hpqNLppsX5P3ros090c54d50';

  late Future<DashboardDataResponse> _future;

  Future<DashboardDataResponse> fetchDashboardList() async {
    final response = await http.get(Uri.parse(_url), headers:{
          'Authorization': 'Bearer $token',
        }, );

    if (response.statusCode == 200) {
      final jsonData = jsonDecode(response.body);
      print("Auth Response Data......: " + jsonData.toString());
      return DashboardDataResponse.fromJson(jsonData);
    } else {
      throw Exception('Failed to load data');
    }
  }

  // Future<Object> fetchDashboardList() async {
  //   try {
  //    // Response response = await _dio.get(_url);
  //     //Response response = await http.post(Uri.parse(_url));
  //     //return DashboardDataResponse.fromJson(response.body as Map<String, dynamic>);
  //
  //     //-------------------------
  //     final response =
  //
  //     await http.post(Uri.parse(_url), headers: {
  //       'Accept': 'application/json',
  //       'Authorization': 'Bearer $token',
  //     }, );
  //     Map<String, dynamic> map = jsonDecode(response.body);
  //     print("Dash Response Data......: " + map.toString());
  //     return DashboardDataResponse.fromJson(map.toString() as Map<String, dynamic>);
  //     //Autogenerated person = Autogenerated.fromJson(map);
  //
  //     //print("Auth Response Data......: " + person.toString());
  //     //print("Auth Response Data......: " + person.errors!.email.toString());
  //
  //     //-------------------------
  //
  //   } catch (error, stacktrace) {
  //     print("Exception occured: $error stackTrace: $stacktrace");
  //     return "Data not found / Connection issue";
  //   }
  // }
}